### ISSUE TITLE
GetAllDatabases returns error 'EOF'

### ISSUE THREAD

**Issue by Avik1993** [akolb1/gometastore#10]
Hi I am running a remote Hive metastore on ec2 machine backed up by MySQL RDS as database.
HiveServer2 service is running on 10002 port.
I already created sample database in hive and a sample table inside it manually.
gometastore library is able to create a connection to Metastore but fails while getting result from GetAllDataases and return EOF error.

```
package main
import	(
    "log"
    "github.com/akolb1/gometastore/hmsclient"
)

func main() {
    client, err := hmsclient.Open("localhost", 10002)
    if err != nil {
	log.Println("Error when creating connection")
        log.Println(err)
    }
    databases, err := client.GetAllDatabases()
    log.Println(client)
    if err != nil {
	log.Println("Error inside GetAllDatabases")
        log.Println(err)
    }
    for _, d := range databases {
	log.Println(d)
    }
}
```

Hive CLI shows 2 dbs:

```
    > show databases;
OK
default
testdb
Time taken: 0.018 seconds, Fetched: 2 row(s)

```

Any help what could be wrong here?

**Comment by akolb1** [comment]
Did you figure out what was the issue?

**Comment by akolb1** [comment]
Are you sure you use the right port for HMS? Usually it is 9083.

**Comment by akolb1** [comment]
The whole goal of this library and tools is to connect to metastore directly.

I am curious what do you want to achieve with this library?

**Comment by Avik1993** [comment]
Correct! Library performs all actions, its been developed for, perfectly fine! Only thing is its connecting to Metastore service over thrift protocol.
I am trying to find if there's some way I connect to Metastore service using JDBC through hiveserver2 service.

**Comment by Avik1993** [comment]
Right! I would want that in future maybe, but I can work with this library only for now.
