### ISSUE TITLE
How do i retrieve all columns with their data type of a table from metastore?

### ISSUE THREAD

**Issue by Avik1993** [akolb1/gometastore#9]
Hi
I am looking to extract all columns of a table using this library. But not able to locate any helpful method for it.
Any help?

**Comment by akolb1** [comment]
Do you need to extract column names and types?

GetTable call which is defined in hmsclient module, returns a Table object.

table.Sd.Cols contains columns information for the table. Columns is a list of FieldSchema objects and FieldSchema is defined as:

type FieldSchema struct {
	Name    string `thrift:"name,1" db:"name" json:"name"`
	Type    string `thrift:"type,2" db:"type" json:"type"`
	Comment string `thrift:"comment,3" db:"comment" json:"comment"`
}

So you can simply walk columns and extract name and type.

Does it make sense?

**Comment by Avik1993** [comment]
Makes sense! Thanks!
